Update installing.rst
building llvmpy requires Python.h for python2.7. If python-dev is not installed here's the error. 

llvmpy/api.cpp:2:20: fatal error: Python.h: No such file or directory
 #include "Python.h"